name: dbt tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dbt-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install dbt-duckdb==1.8.2

      - name: Load seeds and run dbt
        run: |
          cd f1_dbt
          dbt seed
          dbt run
          dbt test